;;;; monarchy-client.import.scm - GENERATED BY CHICKEN 4.8.4 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         json
         http-client
         intarweb
         uri-common
         simple-configuration
         log5scm
         extras
         data-structures
         ports))
(##sys#register-compiled-module
  'monarchy-client
  (list)
  '((push-samples-from . monarchy-client#push-samples-from)
    (invoke-sensor/safe . monarchy-client#invoke-sensor/safe)
    (send-sample-request . monarchy-client#send-sample-request)
    (server-error-details . monarchy-client#server-error-details)
    (client-error-details . monarchy-client#client-error-details)
    (push-samples . monarchy-client#push-samples)
    (serialize-samples/json . monarchy-client#serialize-samples/json)
    (serialize-sample/json . monarchy-client#serialize-sample/json)
    (serialize-fact/json . monarchy-client#serialize-fact/json)
    (sensor/code . monarchy-client#sensor/code)
    (sensor/name . monarchy-client#sensor/name)
    (make-sensor . monarchy-client#make-sensor)
    (sample . monarchy-client#sample)
    (fact/object . monarchy-client#fact/object)
    (fact/predicate . monarchy-client#fact/predicate)
    (fact/subject . monarchy-client#fact/subject)
    (fact . monarchy-client#fact)
    (samples-uri . monarchy-client#samples-uri)
    (uuid . monarchy-client#uuid)
    (fqdn . monarchy-client#fqdn)
    (config-get . monarchy-client#config-get)
    (configuration . monarchy-client#configuration)
    (read-configuration . monarchy-client#read-configuration))
  (list)
  (list))

;; END OF FILE
