;;;; procter.import.scm - GENERATED BY CHICKEN 4.7.0.3-st -*- Scheme -*-

(eval '(import chicken scheme ports extras srfi-1 irregex))
(##sys#register-compiled-module
  'procter
  (list)
  '((with-property-headers . procter#with-property-headers)
    (with-vertical-headers . procter#with-vertical-headers)
    (with-horizontal-headers . procter#with-horizontal-headers)
    (columnize . procter#columnize)
    (make-table-line-reader . procter#make-table-line-reader)
    (make-property-table-reader . procter#make-property-table-reader)
    (make-table-reader . procter#make-table-reader)
    (port-map* . procter#port-map*)
    (make-reader . procter#make-reader)
    (make-fully-qualified-reader . procter#make-fully-qualified-reader)
    (make-procter-error-condition . procter#make-procter-error-condition)
    (make-procter-condition . procter#make-procter-condition)
    (make-exn-condition . procter#make-exn-condition))
  (list)
  (list))

;; END OF FILE
